#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  9 12:07:52 2022

@author: Ya-Chen Chuang
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
import numpy as np
from scipy.stats import mannwhitneyu, normaltest

VolumetricData = pd.read_excel("/Users/kurtlab/Desktop/Chiari_Morphometric/results/morphology_results/morphometric_stat_combine.xlsx", sheet_name='volumetric_combine');



# # statistics
# Healthy = VolumetricData.loc[(VolumetricData.condition == "Healthy"), "whole_tonsil"].values
# Chiari = VolumetricData.loc[(VolumetricData.condition == "Chiari"), "whole_tonsil"].values

# log_Healthy = np.log(Healthy)
# log_Chiari = np.log(Chiari)

# stat_results = [mannwhitneyu(Healthy, Chiari, alternative="two-sided")]
# pvalues = [result.pvalue for result in stat_results]
# print("Healthy vs Chiari: \n", stat_results, "\n")


# # statistical annotation
# x1, x2 = 0, 1   # columns 'Sat' and 'Sun' (first column: 0, see plt.xticks())
# y, h, col = Chiari.max() + 1, .1, 'k'
# plt.plot([x1, x1, x2, x2], [y, y+h, y+h, y], lw=1.5, c=col)
# plt.text((x1+x2)*.5, y+h, "ns", ha='center', va='bottom', color=col)



# Plot
sns.set()
plot = sns.boxplot(x="sex", y = "4thVentricle", hue = "condition", data = VolumetricData);
plot.set_ylabel("4thVentricle volume (mm^3)", fontsize = 20)
plt.xticks(fontsize=20)
plt.yticks(fontsize=14)
plt.show()